---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

A series of meetups about the exploring data with the tidyverse.

## Syllabus

The goal is to lean how to explore data with the tidyverse. At the end of this
series you will be able to do things like these:

* Explore the variation in your data -- visually with ggplot2 and
analytically with dplyr.
* Manipulate and visualize unusual and missing values.
* Explore the covariation between categorical and continuous variables.
* Explore patterns in your data and extract them with a model.

Each item in this syllabus corresponds to a meetup and a GitHub
[release](https://github.com/2DegreesInvesting/ds.docker/releases) that
preserves a snapshot of this repository exactly as it was shown during
thee meetup.

## Prerequisites

This meetup helps you quickly meet the prerequisites for the rest of this
meetup-series. It covers the mimimum elements of a defensive workflow, and of
the data-science toolking you'll need during this series.

Objectives:

* Overview the elements of a defensive workflow and know where to learn more.

## The data science workflow and toolkit: An overview

This meetup overviews the data science workflow and the toolkit you'll need for
the rest of this meetup series.

Objectives:

* Overview the data-science workflow and toolkit.
* Introduce rmarkdown documents.
* Overview the tool for visualization: ggplot2.
* Overview the tool for transformation: dplyr.

## Next

* Explore the variation in your data -- visually with ggplot2 and analytically
with dplyr.
* Manipulate and visualize unusual and missing values.
* Explore the covariation between categorical and continuous variables.
* Explore patterns in your data and extract them with a model.

## Resources

* YouTube [playlist](https://bit.ly/ds-incubator-videos).
* The
[ds-incubator](https://github.com/2DegreesInvesting/ds-incubator#ds-incubator)
project.
* [Ideas](https://bit.ly/dsi-ideas) for future meetups.
* [Exploratory data analysis (R for data
science)](https://r4ds.had.co.nz/exploratory-data-analysis.html).
* Related [issue](https://github.com/2DegreesInvesting/ds-incubator/issues/76).
* [Slides](https://bit.ly/tidy-eda).
